portfolio_type: cards #cards or carousel
production_url: 'https://deliverist.co.uk'
baseurl: ''
encoding: utf-8
syntax_highlighting: true
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
github: [metadata]
